jwtproxy:
  verifier_proxies:
  - listen_addr: :4471
    verifier:
      upstream: http://localhost:8080/
      audience: nil
      max_skew: 1m
      max_ttl: 5m
      key_server:
        type: preshared
        options:
          issuer: jwtproxy
          key_id: mykey
          public_key_path: /etc/jwtproxy/mykey.pub
      claims_verifiers:
      - type: static
        options:
          iss: jwtproxy

    # Key pair used to terminate TLS.
    #key_file: localhost.key
    #crt_file: localhost.crt

  signer_proxy:
    enabled: false
